server:
  port: 8080
spring:
  thymeleaf:
    cache: false
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:oracle:thin:@a3o59xtps8bp4z0y_high?TNS_ADMIN=/Users/junu/study/delicacies-log/wallet/Wallet_A3O59XTPS8BP4Z0Y
    username: admin
    password: 6308Wnsdn@45
    driver-class-name: oracle.jdbc.OracleDriver